apiVersion: v2
name: pulld
description: A Rust pull-through proxy for container registries and Helm artifacts.
type: application
version: 0.2.2
appVersion: "0.3.2"
home: https://github.com/mkoyan44/pulld
sources:
  - https://github.com/mkoyan44/pulld
maintainers:
  - name: mkoyan44
keywords:
  - registry
  - cache
  - proxy
  - oci
  - helm
